urls.py
# Copyright wattTime 2013
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Authors: Sam Marcellus, Anna Schneider, Kevin Yang

from django.views.generic.base import TemplateView

from django.conf.urls import patterns, url, include
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

# basic patterns
urlpatterns = patterns('',
  #  url(r'^data_text/(?P<database>[a-zA-Z0-9_-]+)[/]?$',
  #      'workers.views.data_text_view', name='data_text'),
  #  url(r'^data_json/(?P<database>[a-zA-Z0-9_-]+)[/]?$',
  #      'workers.views.data_json_view', name='data_json'),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

#  allauth patterns
#urlpatterns += patterns('',
#    url(r'accounts[/]',  include('allauth.urls')),
#    url(r'^accounts/profile[/]$', TemplateView.as_view(template_name='account/profile.html')),
#    url(r'^accounts/profile[/]$', 'accounts.views.profile_create', name='user_profile'),
#    url(r'^login/cancelled[/]$', 'login_cancelled', name='socialaccount_login_cancelled'),
#    url(r'^login/error[/]$', 'login_error', name='socialaccount_login_error'),
#)

# invitation patterns
#urlpatterns += patterns('',
#    url(r'accounts[/]',  include('invitation.urls')),
#)

# tools patterns
urlpatterns += patterns('',
    url(r'',  include('watttime_shift.urls')),
)

# pages patterns
urlpatterns += patterns('',
    url(r'',  include('pages.urls')),
)

handler500 = 'pages.views.server_error'
handler404 = 'pages.views.notfound_error'

# accounts patterns
urlpatterns += patterns('',
    url(r'', include('accounts.urls')),
)

# windfriendly API patterns
urlpatterns += patterns('',
    url(r'',  include('windfriendly.urls')),
)

# twilio
urlpatterns += patterns('sms_tools.views',
    url(r'twilio_endpoint', 'twilio_endpoint', name='twilio_endpoint'),
)

# blog
urlpatterns += patterns('',
    url(r'blog/', include('zinnia.urls')),
    url(r'comments[/]', include('django.contrib.comments.urls')),
)

# static
urlpatterns += patterns('',
                        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.STATIC_ROOT }),
                        )

windfriendly/urls.py
# Copyright wattTime 2013
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Authors: Sam Marcellus, Anna Schneider, Kevin Yang

from django.conf.urls import patterns, url, include
from tastypie.api import Api
from . import views
from .api import BA_RESOURCES


v1_api = Api(api_name='v1')
for bar in BA_RESOURCES:
    v1_api.register(bar())

# tastypie resource urls
urlpatterns = patterns('',
    (r'^api/', include(v1_api.urls)),
)

# windfriendly API patterns
urlpatterns += patterns('',
    url(r'^update/(?P<utility>[a-zA-Z0-9_-]+)[/]?$',
        views.update, name='update'),
    url(r'^today[/]?$',
        views.today, name='today'),
    url(r'^averageday[/]?$',
        views.averageday, name='averageday'),
    url(r'^history[/]?$',
        views.history_hourly, name='history'),
    url(r'^greenest_subrange[/]?$',
        views.greenest_subrange, name='greenest_subrange'),
    url(r'^feed/toggle[/]?$',
        views.ToggleFeed(), name='toggle_feed'),
    url(r'^alerts[/]?$',
        views.alerts, name='alerts'),
)

windfriendly/models.py
from django.db import models
import pytz
from .managers import BaseBalancingAuthorityManager, ForecastedBalancingAuthorityManager
from .settings import MARGINAL_FUELS
#from accounts.models import User

class BaseBalancingAuthority(models.Model):
    """Abstract base class for balancing authority timepoints"""
    # must set timezone for every derived class
    TIMEZONE = pytz.utc

    #### COMMON FIELDS ####
    # forecast type is the index in FORECAST_CODES
    forecast_code = models.IntegerField(default=0)
    # date is utc
    date = models.DateTimeField(db_index=True)
    # date_extracted is the UTC time at which these values were pulled from ISO
    date_extracted = models.DateTimeField(db_index=True)
    # fraction_clean is fraction of generation from clean sources (eg wind)
    fraction_clean = models.FloatField(default=0)
    # total_MW is the total amount of generation, if available, or load, if not
    total_MW = models.FloatField(default=0)

    # must define 'date' and 'marginal_fuel' attributes
    def to_dict(self):
        return {'fraction_clean': self.fraction_clean,
                'total_MW': self.total_MW,
                'marginal_fuel': self.marginal_fuel,
                'forecast_code': self.forecast_code,
                'date': self.date.astimezone(pytz.utc).strftime('%Y-%m-%d %H:%M'),
                'date_extracted': self.date_extracted.strftime('%Y-%m-%d %H:%M'),
                'local_date': self.local_date.strftime('%Y-%m-%d %H:%M'),
                }

    class Meta:
        abstract = True
        get_latest_by = 'date'

    def get_title(self):
        return str(self.fraction_clean)

    @property
    def local_date(self):
        """ Time in local timezone """
        return self.date.astimezone(self.TIMEZONE)


class BaseForecastedBalancingAuthority(BaseBalancingAuthority):
    """Abstract base class for balancing authority timepoints with forecasting"""
    class Meta:
        abstract = True
        get_latest_by = 'date'


class CAISO(BaseForecastedBalancingAuthority):
    # use forecasting manager
    objects = ForecastedBalancingAuthorityManager()

    # timezone
    TIMEZONE = pytz.timezone('America/Los_Angeles')

    # load, wind, solar in MW
    load = models.FloatField()
    wind = models.FloatField()
    solar = models.FloatField()

    @property
    def marginal_fuel(self):
        """Integer code for marginal fuel"""
        # implement this as an actual field for BAs with data
        return MARGINAL_FUELS.index('None')


class BPA(BaseBalancingAuthority):
    """Raw BPA data"""
    # use non-forecasted manager
    objects = BaseBalancingAuthorityManager()

    # timezone
    TIMEZONE = pytz.timezone('America/Los_Angeles')

    # load, etc in MW
    load = models.IntegerField()
    wind = models.IntegerField()
    thermal = models.IntegerField()
    hydro = models.IntegerField()

    @property
    def marginal_fuel(self):
        """Integer code for marginal fuel"""
        # implement this as an actual field for BAs with data
        return MARGINAL_FUELS.index('None')


# All units are megawatts
class NE(BaseBalancingAuthority):
    # use non-forecasted manager
    objects = BaseBalancingAuthorityManager()

    # timezone        
    TIMEZONE = pytz.timezone('America/New_York')

    # load, etc in MW
    gas = models.FloatField()
    nuclear = models.FloatField()
    hydro = models.FloatField()
    coal = models.FloatField()
    other_renewable = models.FloatField()
    other_fossil = models.FloatField()
    marginal_fuel = models.IntegerField()


class MISO(BaseForecastedBalancingAuthority):
    # use non-forecasted manager
    objects = BaseBalancingAuthorityManager()

    # timezone        
    TIMEZONE = pytz.timezone('America/Chicago')

    # generation and load in MW
    gas = models.FloatField()
    nuclear = models.FloatField()
    other_gen = models.FloatField() # Hydro, Pumped Storage Hydro, Diesel, Demand Response Resources, External Asynchronous Resources and a varied assortment of solid waste, garbage and wood pulp burners
    coal = models.FloatField()
    wind = models.FloatField()
    load = models.FloatField()

    @property
    def marginal_fuel(self):
        """Integer code for marginal fuel"""
        # implement this as an actual field for BAs with data
        return MARGINAL_FUELS.index('None')


class PJM(BaseForecastedBalancingAuthority):
    """Raw PJM data"""
    # use non-forecasted manager
    objects = BaseBalancingAuthorityManager()

    # timezone
    TIMEZONE = pytz.timezone('US/Eastern')

    # load, etc in MW
    load = models.IntegerField()
    wind = models.IntegerField()

    @property
    def marginal_fuel(self):
        """Integer code for marginal fuel"""
        # implement this as an actual field for BAs with data
        return MARGINAL_FUELS.index('None')


class User(models.Model):
    # name
    name = models.CharField(max_length=100)


class MeterReading(models.Model):
  # user id
  userid = models.ForeignKey(User)

  # energy in kwh
  energy = models.FloatField()

  # duration in seconds
  duration = models.IntegerField()

  # start time in date-time
  start = models.DateTimeField(db_index=True)

  # cost in dollars
  cost = models.FloatField()

  def total_kwh(self):
    return self.energy/3600.0 * self.duration

  def total_cost(self):
    return self.cost * self.duration / 3600.0 / 10000.0

templates/zinnia/_entry_detail_base.html
{% load comments i18n %}
{% load staticfiles %}
<article id="entry-{{ object.pk }}" class="hentry{% if object.featured %} featured{% endif %} panel panel-default">
  {% block entry-header %}
  <div class="entry-header panel-heading">
    {% block entry-title %}
    <h3 class="entry-title">
      <a href="{{ object.get_absolute_url }}" title="{{ object.title }}" rel="bookmark">
        {{ object.title }}
      </a>
    </h3>
    {% endblock entry-title %}
    {% block entry-info %}
        {% for author in object.authors.all %}
          <a href="{{ author.get_absolute_url }}" class="btn btn-default btn-xs fn url{% if not author.get_full_name %} nickname{% endif %}" rel="author"
                 title="{% blocktrans %}Show all {{ author }}'s entries{% endblocktrans %}">
            <span class="glyphicon glyphicon-user"></span> {{ author }}
          </a>
        {% endfor %}

        <a class="btn btn-default btn-xs" href="{% url 'zinnia_entry_archive_day' object.creation_date|date:"Y" object.creation_date|date:"m" object.creation_date|date:"d"%}">
          <span class="glyphicon glyphicon-time"></span>
          <time class="published" datetime="{{ object.creation_date|date:"c" }}" pubdate="pubdate">{{ object.creation_date|date:"DATE_FORMAT" }}</time>
        </a>

        {% for category in object.categories.all %}
          <a href="{{ category.get_absolute_url }}"
           title="{% blocktrans %}Show all entries in {{ category }}{% endblocktrans %}"
           rel="tag category" class="btn btn-default btn-xs">
           <span class="glyphicon glyphicon-th-large"></span> {{ category }}
         </a>
        {% endfor %}

        {% for tag in object.tags_list %}
          <a href="{% url 'zinnia_tag_detail' tag %}"
             title="{% blocktrans %}Show all entries tagged by {{ tag }}{% endblocktrans %}"
             class="btn btn-default btn-xs">
             <span class="glyphicon glyphicon-tag"></span> {{ tag }}
          </a>
        {% endfor %}
    {% endblock entry-info %}
  </div>
  {% endblock entry-header %}



  {% block entry-body %}
  <div class="entry-body panel-body">
    {% block entry-image %}
    {% if object.image %}
    <div class="entry-image">
      <p>
        {% if continue_reading %}
        <a href="{{ object.get_absolute_url }}" title="{{ object.title }}" rel="bookmark">
          {% endif %}
          <img src="{{ object.image.url }}" alt="{{ object.title }}" class="img-thumbnail img-responsive" />
          {% if continue_reading %}
        </a>
        {% endif %}
      </p>
    </div>
    {% endif %}
    {% endblock entry-image %}
    {% block entry-content %}
    <div class="entry-content">
      {{ object_content|safe }}
    </div>
    {% endblock entry-content %}
    {% block continue-reading %}
    {% if continue_reading and object_content.has_more %}
    <p class="continue-reading">
      <a href="{{ object.get_absolute_url }}"
         title="{% blocktrans with object=object.title %}Continue reading {{ object }}{% endblocktrans %}"
         rel="bookmark" class="btn btn-default">
        {% trans "Continue reading" %}
      </a>
    </p>
    {% endif %}
    {% endblock continue-reading %}
  </div>
  {% endblock entry-body %}

  {% block entry-footer %}
  {% endblock entry-footer %}
</article>

templates/zinnia/author_list.html
{% extends "zinnia/base.html" %}
{% load i18n zinnia_tags %}

{% block meta-description %}{% trans "Author list" %}{% endblock meta-description %}

{% block title %}{% trans "Authors" %}{% endblock title %}

{% block body-class %}author-list{% endblock body-class %}

{% block content %}
<div class="panel panel-default">

  <div class="panel-heading">
    <h4>{% trans "Authors" %}</h4>
  </div>

  <ul class="list-group">
    {% for object in object_list %}
    <a class="list-group-item" href="{{object.get_absolute_url}}"
         title="{% blocktrans with author=object %}Show all {{ author }}'s entries{% endblocktrans %}">
        <div class="media">
            <img src="{% get_gravatar object.email 64 %}" class="pull-left media-object">
            <div class="media-body">
              <h3 class="media-heading">{{ object }}</h3>
              <span class="badge">
                {% blocktrans count entry_count=object.count_entries_published %}{{ entry_count }} entry{% plural %}{{ entry_count }} entries{% endblocktrans %}
              </span>
            </div>
        </div>
    </a>
    {% empty %}
    <li class="list-group-item">
      {% trans "No authors yet." %}
    </li>
    {% endfor %}
  </ul>

</div>
{% endblock content %}

templates/zinnia/base.html
{% extends "zinnia/skeleton.html" %}
{% load zinnia_tags i18n %}

{% block meta-keywords %}{% get_tags as entry_tags %}{{ entry_tags|join:", "}}{% endblock meta-keywords %}

{% block meta %}
    <meta name="generator" content="WattTime" />
{% endblock meta %}

{% block link %}
    <link rel="index" href="{% url 'zinnia_entry_archive_index' %}" />
    <link rel="author" type="text/plain" href="{% url 'zinnia_humans' %}" />
    <link rel="EditURI" type="application/rsd+xml" href="{% url 'zinnia_rsd' %}" />
    <link rel="wlwmanifest" type="application/wlwmanifest+xml" href="{% url 'zinnia_wlwmanifest' %}" />
    <link rel="search" type="application/opensearchdescription+xml" title="Zinnia's Weblog" href="{% url 'zinnia_opensearch' %}" />
    <link rel="alternate" type="application/rss+xml" title="{% trans "RSS Feed of latest entries" %}" href="{% url 'zinnia_entry_latest_feed' %}" />
    <link rel="alternate" type="application/rss+xml" title="{% trans "RSS Feed of latest discussions" %}" href="{% url 'zinnia_discussion_latest_feed' %}" />
    {% get_archives_entries "zinnia/tags/entries_archives_link.html" %}
{% endblock link %}

{% block breadcrumbs %}
  {% zinnia_breadcrumbs %}
{% endblock breadcrumbs %}

{% block sidebar %}
<aside id="widget-welcome" class="widget panel panel-default">
  <div class="panel-heading">
    <a href="{% url 'zinnia_entry_archive_index' %}"><span class="glyphicon glyphicon-th-list"></span> {% trans "WattTime Blog" %}</a>
  </div>
  <div class="panel-body">
    <p>
      {% trans "What we're up to, what we care about, and what we've learned." %}
    </p>
      {% include "zinnia/tags/search_form.html" %}
  </div>
  {% get_recent_entries %}
  <ul class="list-group">
    <a href="{% url 'zinnia_entry_archive_year' 2014 %}" class="list-group-item">Archive</a>
    <li class="list-group-item">
      {% include "base_snippets/share.html" %}
    </li>
  </ul>
</aside>

<aside id="widget-meta" class="widget list-group">

    <div class="list-group-item">
        <a href="{% url 'zinnia_author_list' %}" class="btn btn-info">
          <span class="glyphicon glyphicon-user"></span> {% trans "Authors" %}
        </a>
      {% get_authors %}
    </div>

    <div class="list-group-item">
      <a href="{% url 'zinnia_tag_list' %}" class="btn btn-info">
        <span class="glyphicon glyphicon-tags"></span> {% trans "Tags" %}
      </a>
      {% get_tag_cloud %}
    </div>

</aside>

<aside id="widget-navigation" class="widget list-group">
    <a class="list-group-item" href="{% url 'zinnia_entry_latest_feed' %}" title="{% trans "RSS" %}">
        {% trans "RSS" %}
    </a>
    <a class="list-group-item" href="{% url 'zinnia_sitemap' %}" title="{% trans "Sitemap" %}">
        {% trans "Sitemap" %}
    </a>
</aside>

{% if user.is_authenticated %}
<aside id="widget-tools" class="widget panel panel-danger">
  <div class="panel-heading">
    {% trans "Tools" %}
  </div>
  <ul class="list-group">
    {% if perms.zinnia %}
    <a class="list-group-item" href="{% url 'admin:app_list' 'zinnia' %}" title="{% trans "Dashboard" %}">
        <span class="glyphicon glyphicon-book"></span>
        {% trans "Dashboard" %}
    </a>
    {% endif %}
    {% if perms.zinnia.add_entry %}
    <a class="list-group-item" href="{% url 'admin:zinnia_entry_add' %}" title="{% trans "Post an entry" %}">
        <span class="glyphicon glyphicon-pencil"></span>
        {% trans "Post an entry" %}
    </a>
    {% endif %}
    {% block admin-tools %}
    {% endblock admin-tools %}
    <a class="list-group-item" href="{% url 'admin:logout' %}" title="{% trans "Log out" %}">
        <span class="glyphicon glyphicon-off"></span>
        {% trans "Log out" %}
    </a>
  </ul>
</aside>
{% endif %}
{% endblock sidebar %}

templates/zinnia/category_list.html
{% extends "zinnia/base.html" %}
{% load i18n mptt_tags %}

{% block meta-description %}{% trans "Category list" %}{% endblock meta-description %}

{% block title %}{% trans "Categories" %}{% endblock title %}

{% block body-class %}category-list{% endblock body-class %}

{% block content %}
<div class="panel panel-default">

  <div class="panel-heading">
    <h4>{% trans "Categories" %}</h4>
  </div>

  <ul class="category-root list-group">
    {% recursetree object_list %}
    <a class="list-group-item" href="{{node.get_absolute_url}}"
         title="{% blocktrans with category=node %}Show all {{ author }}'s entries{% endblocktrans %}">

      {{ node }}
      <span class="badge">
        {% blocktrans count entry_count=node.entries_published.count %}{{ entry_count }} entry{% plural %}{{ entry_count }} entries{% endblocktrans %}
      </span>

      {% if node.description %}<p>{{ node.description|striptags|safe }}</p>{% endif %}

      {% if not node.is_leaf_node %}
      <ul class="category-children category-{{ node.slug }}">
        {{ children }}
      </ul>
      {% endif %}

    </a>
    {% endrecursetree %}

    {% if not object_list %}
    <li class="list-group-item">
      {% trans "No categories yet." %}
    </li>
    {% endif %}
  </ul>

</div>
{% endblock content %}

templates/zinnia/entry_list.html
{% extends "zinnia/base.html" %}
{% load i18n zinnia_tags %}

{% block meta-description %}{% trans "Latest entries for" %} {% if category %}{% trans "the category" %} {{ category }}{% if category.description %}: {{ category.description|striptags|safe }}{% endif %}{% endif %}{% if tag %}{% trans "the tag" %} {{ tag }}{% endif %}{% if author %}{% trans "the author" %} {{ author }}{% endif %}{% endblock meta-description %}

{% block meta-description-page %}{% if page_obj %}{% ifnotequal page_obj.number 1 %} {% trans "page" %} {{ page_obj.number }}{% endifnotequal %}{% endif %}{% endblock meta-description-page %}

{% block link %}
  {{ block.super }}
  {% if category %}
    <link rel="alternate" type="application/rss+xml" title="{% trans "RSS Feed" %} {{ category }}" href="{% url 'zinnia:category_feed' category.tree_path %}" />
  {% endif %}
  {% if tag %}
    <link rel="alternate" type="application/rss+xml" title="{% trans "RSS Feed" %} {{ tag }}" href="{% url 'zinnia:tag_feed' tag.name %}" />
  {% endif %}
  {% if author %}
    <link rel="alternate" type="application/rss+xml" title="{% trans "RSS Feed" %} {{ author }}" href="{% url 'zinnia:author_feed' author.get_username %}" />
  {% endif %}
{% endblock link %}

{% block title %}{% if category %}{% trans "Category" %} {{ category }}{% endif %}{% if tag %}{% trans "Tag" %} {{ tag }}{% endif %}{% if author %}{% trans "Author" %} {{ author }}{% endif %}{% endblock title %}

{% block title-page %}{% if page_obj %}{% ifnotequal page_obj.number 1 %} - {% trans "Page" %} {{ page_obj.number }}{% endifnotequal %}{% endif %}{% endblock title-page %}

{% block body-class %}entry-list{% if page_obj %} paginated page-{{ page_obj.number }}{% endif %}{% if category %} category category-{{ category.slug }}{% endif %}{% if tag %} tag tag-{{ tag|slugify }}{% endif %}{% if author %} author author-{{ author|slugify }}{% endif %}{% endblock body-class %}

{% block content %}

{% block content-title %}
  {% if category %}
  <div class="panel panel-default">
    <div class="panel-body">
      <h3>{{ category }}</h3>
      {% if category.description %}
      <p>{{ category.description|striptags|safe }}</p>
      {% endif %}
    </div>
  </div>
  {% endif %}

  {% if author %}
  <div class="panel panel-default">
    <div class="panel-body">
        <div class="media">
            <img src="{% get_gravatar author.email 64 %}" class="pull-left media-object">
            <div class="media-body">
              <h3 class="media-heading">{{ author }}</h3>
            </div>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock content-title %}

{% block content-loop %}
{% for object in object_list %}
  {% include object.content_template with object_content=object.html_preview continue_reading=1 %}
{% empty %}
  <p class="info">
    <a href="{% url 'admin:zinnia_entry_add' %}">{% trans "No entries yet." %}</a>
  </p>
{% endfor %}
{% endblock content-loop %}

{% block content-pagination %}
{% if is_paginated %}
  {% zinnia_pagination page_obj %}
{% endif %}
{% endblock content-pagination %}

{% endblock content %}

{% block admin-tools %}
  {% if category and perms.zinnia.change_category %}
  <a href="{% url 'admin:zinnia_category_change' category.pk %}" title="{% trans "Edit the category" %}" class="list-group-item">
    <span class="glyphicon glyphicon-edit"></span>
      {% trans "Edit the category" %}
  </a>
  {% endif %}
  {% if tag and perms.tagging.change_tag %}
  <a href="{% url 'admin:tagging_tag_change' tag.pk %}" title="{% trans "Edit the tag" %}" class="list-group-item">
    <span class="glyphicon glyphicon-edit"></span>
    {% trans "Edit the tag" %}
  </a>
  {% endif %}
  {% if author and perms.auth.change_user %}
  <a href="{% url 'change'|user_admin_urlname author.pk %}" title="{% trans "Edit the author" %}"  class="list-group-item">
    <span class="glyphicon glyphicon-edit"></span>
    {% trans "Edit the author" %}
  </a>
  {% endif %}
{% endblock admin-tools %}

templates/zinnia/entry_search.html
{% extends "zinnia/entry_list.html" %}
{% load i18n zinnia_tags %}

{% block title %}{% trans "Search results for" %} '{{ pattern }}'{% endblock title %}

{% block meta-description %}{% trans "Search results for" %} '{{ pattern }}'{% endblock meta-description %}

{% block link %}
  {{ block.super }}
  <link rel="alternate" type="application/rss+xml" title="{% trans "RSS Feed of search result of" %} '{{ pattern }}'" href="{% url 'zinnia:entry_search_feed' %}?pattern={{ pattern }}" />
{% endblock link %}

{% block body-class %}{{ block.super }} search {% if object_list %}search-results{% else %}search-no-results{% endif %}{% endblock body-class %}

{% block content-title %}

{% if error %}
<div class="alert alert-danger">
	<strong>{% trans "Search results for" %} '{{ pattern }}'</strong>:
	{{ error }}
</div>
{% endif %}

{% if object_list %}
<div class="alert alert-success">
	<strong>{% trans "Search results for" %} '{{ pattern }}'</strong>:
  {% blocktrans count entry_count=paginator.count %}{{ entry_count }} entry found{% plural %}{{ entry_count }} entries found{% endblocktrans %}
</div>
{% endif %}
{% endblock content-title %}

{% block content-loop %}
{% if not error %}
{% for object in object_list %}
  {% include object.content_template with object_content=object.html_preview continue_reading=1 %}
{% empty %}
<div class="alert alert-warning">
	<strong>{% trans "Search results for" %} '{{ pattern }}'</strong>:
	Nothing found.
</div>
{% endfor %}
{% endif %}
{% endblock content-loop %}

{% block content-related %}
<div class="search">
  {% include "zinnia/tags/search_form.html" %}
</div>
{% endblock content-related %}

templates/zinnia/tag_list.html
{% extends "zinnia/base.html" %}
{% load i18n %}

{% block meta-description %}{% trans "Tag list" %}{% endblock meta-description %}

{% block title %}{% trans "Tags" %}{% endblock title %}

{% block body-class %}tag-list{% endblock body-class %}


{% block content %}
<div class="panel panel-default">

  <div class="panel-heading">
    <h4>{% trans "Tags" %}</h4>
  </div>

  <ul class="list-group">
    {% for object in object_list %}
    <a class="list-group-item" href="{% url 'zinnia_tag_detail' object %}"
         title="{% blocktrans with tag=object %}Show all entries tagged by {{ tag }}{% endblocktrans %}">{{ object }}
      <span class="badge">
        {% blocktrans count entry_count=object.count %}{{ entry_count }} entry{% plural %}{{ entry_count }} entries{% endblocktrans %}
      </span>
    </a>
    {% empty %}
    <li>
      {% trans "No tags yet." %}
    </li>
    {% endfor %}
  </ul>

</div>
{% endblock content %}